"""Update User table: added request col

Revision ID: ed0f086f7609
Revises: 9e030ded8327
Create Date: 2026-03-11 22:24:57.835765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed0f086f7609'
down_revision: Union[str, Sequence[str], None] = '9e030ded8327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('request', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'last_login_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('user', 'request')
    # ### end Alembic commands ###